version: '1'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: builder:latest
    container_name: my_go_app_builder

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go_app:latest
    container_name: my_go_app_container
    depends_on:
      - builder
